[package]
name = "birthday_letter_generator"
version = "0.1.0"
edition = "2018"

[dependencies]
sha1 = "0.10.6"
hmac = "0.12.1"
zip = "0.6"
time = { version = "0.3", features = ["std"] }
rand = "0.8"
